CREATE SCHEMA IF NOT EXISTS wstest;
CREATE TABLE IF NOT EXISTS Article (
  ARTICLE_ID BIGINT auto_increment PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(255),
  CATEGORY VARCHAR(50),
  PRICE NUMERIC,
  ADDRESS VARCHAR(50) NOT NULL,
  MODIFIEDDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Comment (
  COMMENT_ID BIGINT auto_increment PRIMARY KEY,
  TEXT VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL ,
  ARTICLE_ID BIGINT,
  MODIFIEDDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ARTICLE_ID) REFERENCES Article(ARTICLE_ID)
);
